# Generated by Django 3.0 on 2021-01-20 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210120_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='full_name',
            field=models.CharField(default="123", max_length=30),
            preserve_default=False,
        ),
    ]
