# Generated by Django 3.0 on 2021-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210121_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_word',
            field=models.CharField(max_length=50),
        ),
    ]
