# Generated by Django 3.0 on 2021-01-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210121_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_word',
        ),
    ]
