# Generated by Django 3.0 on 2021-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_role_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=30),
        ),
    ]
