# Generated by Django 3.0 on 2021-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('pass_series', models.CharField(max_length=5)),
                ('pass_number', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
