# Generated by Django 3.0 on 2021-01-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, max_length=80, null=True, upload_to='')),
                ('contact', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('dealer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.DealerType')),
            ],
        ),
    ]
