# Generated by Django 3.0 on 2021-01-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.CharField(max_length=25)),
                ('vin', models.CharField(max_length=25)),
                ('release_year', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('color', models.CharField(max_length=15)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('wheel', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('engine_power', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.BodyType')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DrivetrainType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(blank=True, max_length=350, null=True)),
                ('image', models.ImageField(blank=True, max_length=80, null=True, upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.DefectType')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer'),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.DrivetrainType'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.EngineType'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.TransmissionType'),
        ),
    ]
